export const wikiManifest = {
  title: "LLM Wiki Starter",
  updated: "2026-05-05",
  pages: [
    {
      path: "wiki/index.md",
      title: "Wiki Index",
      tags: ["home", "navigation"],
      summary: "Content catalog for the whole LLM-maintained wiki.",
    },
    {
      path: "wiki/overview.md",
      title: "Overview",
      tags: ["synthesis"],
      summary: "The standing synthesis of this vault and how it should evolve.",
    },
    {
      path: "wiki/log.md",
      title: "Log",
      tags: ["operations"],
      summary: "Append-only activity ledger for ingests, queries, and lint passes.",
    },
    {
      path: "wiki/sources/karpathy-llm-wiki.md",
      title: "Karpathy LLM Wiki Pattern",
      tags: ["source", "pattern"],
      summary: "A local synthesis of Andrej Karpathy's LLM wiki idea.",
    },
    {
      path: "wiki/sources/microsoft-m-memory-harness.md",
      title: "Microsoft M*: Self-Evolving Memory Harness",
      tags: ["source", "memory", "agent"],
      summary: "A synthesis of the M* paper and its task-specific memory lesson.",
    },
    {
      path: "wiki/concepts/compilation-over-retrieval.md",
      title: "Compilation Over Retrieval",
      tags: ["concept"],
      summary: "Why this wiki compiles durable knowledge instead of only retrieving chunks.",
    },
    {
      path: "wiki/concepts/memory-harness.md",
      title: "Memory Harness",
      tags: ["concept", "memory", "agent"],
      summary: "Task-specific memory design for agents and this wiki.",
    },
    {
      path: "wiki/columns/ai-se-testing/index.md",
      title: "AI SE Testing Column",
      tags: ["column", "testing", "ai-se"],
      summary: "Reading hub for AI-assisted automated software engineering testing.",
    },
    {
      path: "wiki/columns/ai-se-testing/reading-list.md",
      title: "AI SE Testing Reading List",
      tags: ["column", "testing", "sources"],
      summary: "Curated primary sources for AI testing, SWE agents, and CI evaluation.",
    },
    {
      path: "wiki/columns/ai-se-testing/test-generation.md",
      title: "Test Generation",
      tags: ["column", "testing", "generation"],
      summary: "Patterns for LLM-assisted test generation and verification loops.",
    },
    {
      path: "wiki/columns/ai-se-testing/swe-agent-evaluation.md",
      title: "SWE Agent Evaluation",
      tags: ["column", "benchmark", "agent"],
      summary: "How SWE benchmarks evaluate repository-level coding and testing agents.",
    },
    {
      path: "wiki/columns/ai-se-testing/ci-and-regression.md",
      title: "CI And Regression",
      tags: ["column", "ci", "regression"],
      summary: "Long-running correctness and regression testing for AI software agents.",
    },
    {
      path: "wiki/columns/ai-se-testing/testing-frameworks.md",
      title: "Testing Frameworks",
      tags: ["column", "testing", "frameworks"],
      summary: "Framework criteria for AI agents that generate, run, and maintain tests.",
    },
    {
      path: "agent/profile.md",
      title: "Wiki Agent Profile",
      tags: ["agent", "memory"],
      summary: "Identity and responsibilities for the wiki-maintaining agent.",
      audience: "maintenance",
    },
    {
      path: "agent/operating-rules.md",
      title: "Wiki Agent Operating Rules",
      tags: ["agent", "memory", "workflow"],
      summary: "Rules for repo memory, private overlays, source ingest, and changes.",
      audience: "maintenance",
    },
    {
      path: "agent/memory/decisions.md",
      title: "Agent Decisions",
      tags: ["agent", "memory"],
      summary: "Durable project-level decisions for the wiki agent.",
      audience: "maintenance",
    },
    {
      path: "agent/memory/source-ledger.md",
      title: "Source Ledger",
      tags: ["agent", "source", "memory"],
      summary: "Sources that have been ingested into the wiki.",
      audience: "maintenance",
    },
    {
      path: "agent/memory/user-preferences.md",
      title: "User Preferences",
      tags: ["agent", "memory"],
      summary: "Non-sensitive collaboration preferences safe for the public repo.",
      audience: "maintenance",
    },
    {
      path: "agent/memory/open-questions.md",
      title: "Open Questions",
      tags: ["agent", "planning"],
      summary: "Unresolved design questions for future wiki evolution.",
      audience: "maintenance",
    },
    {
      path: "agent/memory/concepts.md",
      title: "Agent Concepts",
      tags: ["agent", "concept"],
      summary: "Recurring concepts tracked by the wiki agent.",
      audience: "maintenance",
    },
    {
      path: "wiki/workflows/ingest.md",
      title: "Ingest Workflow",
      tags: ["workflow"],
      summary: "How to add one new source and update the wiki coherently.",
    },
    {
      path: "wiki/workflows/query.md",
      title: "Query Workflow",
      tags: ["workflow"],
      summary: "How to answer questions from the wiki and file useful answers back.",
    },
    {
      path: "wiki/workflows/lint.md",
      title: "Lint Workflow",
      tags: ["workflow"],
      summary: "How to health-check links, contradictions, stale claims, and gaps.",
    },
    {
      path: "agent/skills/ingest-source.md",
      title: "Agent Skill: Ingest Source",
      tags: ["agent", "skill", "workflow"],
      summary: "The agent's repeatable process for ingesting external sources.",
      audience: "maintenance",
    },
    {
      path: "agent/skills/synthesize-page.md",
      title: "Agent Skill: Synthesize Page",
      tags: ["agent", "skill", "workflow"],
      summary: "The agent's repeatable process for writing useful wiki pages.",
      audience: "maintenance",
    },
    {
      path: "agent/skills/maintain-memory.md",
      title: "Agent Skill: Maintain Memory",
      tags: ["agent", "skill", "memory"],
      summary: "The agent's rules for repo memory and private overlays.",
      audience: "maintenance",
    },
    {
      path: "agent/skills/propose-pr.md",
      title: "Agent Skill: Propose PR",
      tags: ["agent", "skill", "github"],
      summary: "The agent's publication workflow for GitHub changes.",
      audience: "maintenance",
    },
    {
      path: "wiki/meta/project-maintenance.md",
      title: "Project Maintenance",
      tags: ["meta", "agent", "maintenance"],
      summary: "Maintenance-only index for the wiki agent workspace and skills.",
      audience: "maintenance",
    },
  ],
};
